# vulpes-reddishnovember-light - ZSH Theme
# Generated by vulpes-theme-lab
# Add this to your ~/.zshrc

# ZSH Syntax Highlighting
# Requires: https://github.com/zsh-users/zsh-syntax-highlighting
# Note: Uses 256-color palette (0-255)
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='fg=89'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=161,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=16,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=30'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=30'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=30'
ZSH_HIGHLIGHT_STYLES[function]='fg=30'
ZSH_HIGHLIGHT_STYLES[command]='fg=30'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=30'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=162'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=30'
ZSH_HIGHLIGHT_STYLES[path]='fg=16'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=162'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=16'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=162'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=161'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=163'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=198'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=198'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=16'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=16'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=16'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=16'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=198'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=198'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=198'
ZSH_HIGHLIGHT_STYLES[assign]='fg=198'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=162'
ZSH_HIGHLIGHT_STYLES[comment]='fg=16'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=30'

# FZF Colors
# Requires: https://github.com/junegunn/fzf
# Note: Uses hex colors (#RRGGBB format)
export FZF_DEFAULT_OPTS="\
--color=fg:#501630,bg:#f7f7f7,hl:#fa0070 \
--color=fg+:#501630,bg+:#efefef,hl+:#fa0070 \
--color=info:#e00083,prompt:#fa0070,pointer:#fa0070 \
--color=marker:#d60044,spinner:#e0001e,header:#000000 \
--color=border:#efefef,label:#501630,query:#501630"

# Powerlevel10k Colors
# Requires: https://github.com/romkatv/powerlevel10k
# Add these to your ~/.p10k.zsh before the line that says 'source ${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh'
# Note: Uses 256-color palette (0-255) and POWERLEVEL9K_ prefix
# Foreground colors are automatically calculated for optimal contrast using chroma-js
typeset -g POWERLEVEL9K_DIR_BACKGROUND=198
typeset -g POWERLEVEL9K_DIR_FOREGROUND=231
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=161
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=231
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=161
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=231
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=163
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=231
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=161
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=231
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=161
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=231
