# vulpes-reddishnovember-dark - ZSH Theme
# Generated by vulpes-theme-lab
# Add this to your ~/.zshrc

# ZSH Syntax Highlighting
# Requires: https://github.com/zsh-users/zsh-syntax-highlighting
# Note: Uses 256-color palette (0-255)
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='fg=224'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=197,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=206,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=123'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=123'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=123'
ZSH_HIGHLIGHT_STYLES[function]='fg=123'
ZSH_HIGHLIGHT_STYLES[command]='fg=123'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=123'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=204'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=123'
ZSH_HIGHLIGHT_STYLES[path]='fg=209'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=204'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=209'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=204'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=197'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=199'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=199'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=199'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=209'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=209'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=209'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=209'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=199'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=199'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=199'
ZSH_HIGHLIGHT_STYLES[assign]='fg=199'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=204'
ZSH_HIGHLIGHT_STYLES[comment]='fg=231'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=123'

# FZF Colors
# Requires: https://github.com/junegunn/fzf
# Note: Uses hex colors (#RRGGBB format)
export FZF_DEFAULT_OPTS="\
--color=fg:#f2cfdf,bg:#0d0d0d,hl:#e60067 \
--color=fg+:#f2cfdf,bg+:#1a1a1a,hl+:#e60067 \
--color=info:#ff0095,prompt:#e60067,pointer:#e60067 \
--color=marker:#ffffff,spinner:#ff0022,header:#ffffff \
--color=border:#1a1a1a,label:#f2cfdf,query:#f2cfdf"

# Powerlevel10k Colors
# Requires: https://github.com/romkatv/powerlevel10k
# Add these to your ~/.p10k.zsh before the line that says 'source ${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh'
# Note: Uses 256-color palette (0-255) and POWERLEVEL9K_ prefix
# Foreground colors are automatically calculated for optimal contrast using chroma-js
typeset -g POWERLEVEL9K_DIR_BACKGROUND=198
typeset -g POWERLEVEL9K_DIR_FOREGROUND=231
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=231
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=16
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=197
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=231
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=199
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=231
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=231
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=16
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=197
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=231

# Man page colors (LESS_TERMCAP) - light pink pops on dark bg
export LESS_TERMCAP_mb=$'\e[1;38;5;204m'      # begin bold - pink
export LESS_TERMCAP_md=$'\e[1;38;5;204m'      # begin blink - pink (headers)
export LESS_TERMCAP_me=$'\e[0m'               # end bold/blink
export LESS_TERMCAP_so=$'\e[38;5;0;48;5;174m' # standout - dark on dusty rose
export LESS_TERMCAP_se=$'\e[0m'               # end standout
export LESS_TERMCAP_us=$'\e[4;38;5;167m'      # underline - orange-red
export LESS_TERMCAP_ue=$'\e[0m'               # end underline
