-- vulpes-reddishnovember-dark colorscheme
-- Generated by vulpes-theme-lab
-- Comprehensive highlight groups (100+) for maximum legibility

local M = {}

function M.setup()
  vim.cmd('hi clear')
  if vim.fn.exists('syntax_on') then
    vim.cmd('syntax reset')
  end

  vim.o.background = 'dark'
  vim.g.colors_name = 'vulpes-reddishnovember-dark'

  local colors = {
    bg = '#0d0d0d',
    bg_alt = '#1a1a1a',
    fg = '#f2cfdf',
    base = '#e60067',

    error = '#ff001e',
    warning = '#ff0022',
    success = '#ffffff',
    info = '#ff0095',
    hint = '#ff4d9d',

    comment = '#ffffff',
    keyword = '#ff1aca',
    string = '#ff7f29',
    number = '#ff33c5',
    boolean = '#ff1043',
    func = '#ff0022',
    const = '#ff1043',
    type = '#ff24ab',
    variable = '#ff0a89',
    operator = '#ff1a79',
    builtin = '#ff1053',
    parameter = '#ff057e',
    property = '#ff0a91',
    namespace = '#ff1f6d',
    macro = '#ff159d',
    tag = '#ff1a62',
    punctuation = '#ff006f',
    heading = '#ff2453',

    selection = '#ff0022',
    cursor = '#e60067',
    cursorline = '#141414',
  }

  local highlights = {
    -- ============================================================================
    -- EDITOR UI
    -- ============================================================================
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg_alt },
    NormalNC = { fg = colors.fg, bg = colors.bg },
    FloatBorder = { fg = colors.base, bg = colors.bg_alt },
    FloatTitle = { fg = colors.base, bg = colors.bg_alt },

    Cursor = { fg = colors.bg, bg = colors.cursor },
    lCursor = { link = 'Cursor' },
    CursorIM = { link = 'Cursor' },
    TermCursor = { link = 'Cursor' },
    TermCursorNC = { fg = colors.bg, bg = colors.comment },

    CursorLine = { bg = colors.cursorline },
    CursorColumn = { bg = colors.cursorline },
    CursorLineNr = { fg = colors.base },
    LineNr = { fg = colors.comment },
    LineNrAbove = { fg = colors.comment },
    LineNrBelow = { fg = colors.comment },

    SignColumn = { bg = colors.bg },
    SignColumnSB = { link = 'SignColumn' },
    FoldColumn = { fg = colors.comment, bg = colors.bg },
    Folded = { fg = colors.comment, bg = colors.bg_alt },
    ColorColumn = { bg = colors.bg_alt },

    -- Selections & Search
    Visual = { bg = colors.selection },
    VisualNOS = { bg = colors.selection },
    Search = { fg = colors.bg, bg = colors.warning },
    IncSearch = { fg = colors.bg, bg = colors.base },
    CurSearch = { fg = colors.bg, bg = colors.base },
    Substitute = { fg = colors.bg, bg = colors.error },

    -- UI Elements
    Pmenu = { fg = colors.fg, bg = colors.bg_alt },
    PmenuSel = { fg = colors.bg, bg = colors.base },
    PmenuSbar = { bg = colors.bg_alt },
    PmenuThumb = { bg = colors.base },
    PmenuKind = { fg = colors.type, bg = colors.bg_alt },
    PmenuKindSel = { fg = colors.bg, bg = colors.type },
    PmenuExtra = { fg = colors.comment, bg = colors.bg_alt },
    PmenuExtraSel = { fg = colors.bg, bg = colors.comment },

    StatusLine = { fg = colors.fg, bg = colors.bg_alt },
    StatusLineNC = { fg = colors.comment, bg = colors.bg },
    WinBar = { fg = colors.fg, bg = colors.bg },
    WinBarNC = { fg = colors.comment, bg = colors.bg },

    TabLine = { fg = colors.comment, bg = colors.bg },
    TabLineFill = { bg = colors.bg },
    TabLineSel = { fg = colors.fg, bg = colors.bg_alt },

    VertSplit = { fg = colors.bg_alt },
    WinSeparator = { fg = colors.bg_alt },

    Title = { fg = colors.base },
    Directory = { fg = colors.info },
    Question = { fg = colors.success },
    MoreMsg = { fg = colors.success },
    ModeMsg = { fg = colors.base },
    WarningMsg = { fg = colors.warning },
    ErrorMsg = { fg = colors.error },

    Conceal = { fg = colors.comment },
    NonText = { fg = colors.comment },
    SpecialKey = { fg = colors.comment },
    Whitespace = { fg = colors.comment },
    EndOfBuffer = { fg = colors.bg },

    -- Spell checking
    SpellBad = { sp = colors.error, undercurl = true },
    SpellCap = { sp = colors.warning, undercurl = true },
    SpellLocal = { sp = colors.info, undercurl = true },
    SpellRare = { sp = colors.hint, undercurl = true },

    -- ============================================================================
    -- CORE SYNTAX HIGHLIGHTING
    -- ============================================================================
    Comment = { fg = colors.comment },
    SpecialComment = { fg = colors.comment },

    Constant = { fg = colors.const },
    String = { fg = colors.string },
    Character = { fg = colors.string },
    Number = { fg = colors.number },
    Boolean = { fg = colors.boolean },
    Float = { fg = colors.number },

    Identifier = { fg = colors.variable },
    Function = { fg = colors.func },

    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.keyword },
    Repeat = { fg = colors.keyword },
    Label = { fg = colors.keyword },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword },
    Exception = { fg = colors.error },

    PreProc = { fg = colors.base },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Macro = { fg = colors.macro },
    PreCondit = { fg = colors.keyword },

    Type = { fg = colors.type },
    StorageClass = { fg = colors.keyword },
    Structure = { fg = colors.type },
    Typedef = { fg = colors.type },

    Special = { fg = colors.base },
    SpecialChar = { fg = colors.base },
    Tag = { fg = colors.tag },
    Delimiter = { fg = colors.punctuation },
    Debug = { fg = colors.warning },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    Ignore = { fg = colors.comment },
    Error = { fg = colors.error },
    Todo = { fg = colors.bg, bg = colors.warning },

    -- ============================================================================
    -- LSP DIAGNOSTICS
    -- ============================================================================
    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticOk = { fg = colors.success },

    DiagnosticVirtualTextError = { fg = colors.error, bg = colors.bg },
    DiagnosticVirtualTextWarn = { fg = colors.warning, bg = colors.bg },
    DiagnosticVirtualTextInfo = { fg = colors.info, bg = colors.bg },
    DiagnosticVirtualTextHint = { fg = colors.hint, bg = colors.bg },

    DiagnosticUnderlineError = { sp = colors.error },
    DiagnosticUnderlineWarn = { sp = colors.warning, underline = true },
    DiagnosticUnderlineInfo = { sp = colors.info, underline = true },
    DiagnosticUnderlineHint = { sp = colors.hint, underline = true },

    DiagnosticFloatingError = { fg = colors.error, bg = colors.bg_alt },
    DiagnosticFloatingWarn = { fg = colors.warning, bg = colors.bg_alt },
    DiagnosticFloatingInfo = { fg = colors.info, bg = colors.bg_alt },
    DiagnosticFloatingHint = { fg = colors.hint, bg = colors.bg_alt },

    DiagnosticSignError = { fg = colors.error, bg = colors.bg },
    DiagnosticSignWarn = { fg = colors.warning, bg = colors.bg },
    DiagnosticSignInfo = { fg = colors.info, bg = colors.bg },
    DiagnosticSignHint = { fg = colors.hint, bg = colors.bg },

    -- LSP Semantic Token Groups
    ['@lsp.type.class'] = { link = 'Type' },
    ['@lsp.type.decorator'] = { link = 'Function' },
    ['@lsp.type.enum'] = { link = 'Type' },
    ['@lsp.type.enumMember'] = { link = 'Constant' },
    ['@lsp.type.function'] = { link = 'Function' },
    ['@lsp.type.interface'] = { link = 'Type' },
    ['@lsp.type.macro'] = { link = 'Macro' },
    ['@lsp.type.method'] = { link = 'Function' },
    ['@lsp.type.namespace'] = { fg = colors.namespace },
    ['@lsp.type.parameter'] = { fg = colors.parameter },
    ['@lsp.type.property'] = { fg = colors.property },
    ['@lsp.type.struct'] = { link = 'Type' },
    ['@lsp.type.type'] = { link = 'Type' },
    ['@lsp.type.typeParameter'] = { link = 'Type' },
    ['@lsp.type.variable'] = { link = '@variable' },

    -- ============================================================================
    -- TREESITTER - COMPREHENSIVE LANGUAGE SUPPORT
    -- ============================================================================

    -- Comments
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { fg = colors.comment },
    ['@comment.error'] = { fg = colors.error },
    ['@comment.warning'] = { fg = colors.warning },
    ['@comment.todo'] = { fg = colors.bg, bg = colors.warning },
    ['@comment.note'] = { fg = colors.info },

    -- Constants
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = colors.const },
    ['@constant.macro'] = { link = 'Macro' },

    -- Strings
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { fg = colors.string },
    ['@string.regex'] = { fg = colors.warning },
    ['@string.escape'] = { fg = colors.base },
    ['@string.special'] = { fg = colors.base },
    ['@string.special.symbol'] = { fg = colors.const },
    ['@string.special.url'] = { fg = colors.info, underline = true },

    -- Characters & Numbers
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@boolean'] = { link = 'Boolean' },

    -- Functions
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = colors.builtin },
    ['@function.call'] = { fg = colors.func },
    ['@function.macro'] = { link = 'Macro' },
    ['@function.method'] = { fg = colors.func },
    ['@function.method.call'] = { fg = colors.func },

    -- Constructors
    ['@constructor'] = { fg = colors.type },

    -- Keywords
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.return'] = { fg = colors.keyword },
    ['@keyword.function'] = { fg = colors.keyword },
    ['@keyword.operator'] = { fg = colors.operator },
    ['@keyword.import'] = { link = 'Include' },
    ['@keyword.exception'] = { link = 'Exception' },
    ['@keyword.directive'] = { link = 'PreProc' },
    ['@keyword.directive.define'] = { link = 'Define' },

    -- Operators
    ['@operator'] = { link = 'Operator' },

    -- Variables
    ['@variable'] = { fg = colors.variable },
    ['@variable.builtin'] = { fg = colors.builtin },
    ['@variable.parameter'] = { fg = colors.parameter },
    ['@variable.parameter.builtin'] = { fg = colors.builtin },
    ['@variable.member'] = { fg = colors.property },

    -- Types
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { fg = colors.builtin },
    ['@type.definition'] = { link = 'Typedef' },
    ['@type.qualifier'] = { link = 'Keyword' },

    -- Attributes & Properties
    ['@attribute'] = { fg = colors.base },
    ['@attribute.builtin'] = { fg = colors.builtin },
    ['@property'] = { fg = colors.property },
    ['@field'] = { fg = colors.property },

    -- Modules & Namespaces
    ['@module'] = { fg = colors.namespace },
    ['@module.builtin'] = { fg = colors.builtin },
    ['@label'] = { link = 'Label' },

    -- Punctuation
    ['@punctuation.delimiter'] = { fg = colors.punctuation },
    ['@punctuation.bracket'] = { fg = colors.punctuation },
    ['@punctuation.special'] = { fg = colors.punctuation },

    -- Tags (HTML/XML/JSX)
    ['@tag'] = { fg = colors.tag },
    ['@tag.builtin'] = { fg = colors.builtin },
    ['@tag.attribute'] = { fg = colors.property },
    ['@tag.delimiter'] = { fg = colors.punctuation },

    -- Markup (Markdown, etc.)
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.underline'] = { underline = true },

    ['@markup.heading'] = { fg = colors.heading },
    ['@markup.heading.1'] = { fg = colors.heading },
    ['@markup.heading.2'] = { fg = colors.heading },
    ['@markup.heading.3'] = { fg = colors.heading },
    ['@markup.heading.4'] = { fg = colors.heading },
    ['@markup.heading.5'] = { fg = colors.heading },
    ['@markup.heading.6'] = { fg = colors.heading },

    ['@markup.quote'] = { fg = colors.comment },
    ['@markup.math'] = { fg = colors.number },

    ['@markup.link'] = { fg = colors.info, underline = true },
    ['@markup.link.label'] = { fg = colors.string },
    ['@markup.link.url'] = { fg = colors.info, underline = true },

    ['@markup.raw'] = { fg = colors.string },
    ['@markup.raw.block'] = { fg = colors.string },

    ['@markup.list'] = { fg = colors.base },
    ['@markup.list.checked'] = { fg = colors.success },
    ['@markup.list.unchecked'] = { fg = colors.comment },

    -- Diffs
    ['@diff.plus'] = { fg = colors.success },
    ['@diff.minus'] = { fg = colors.error },
    ['@diff.delta'] = { fg = colors.warning },

    -- ============================================================================
    -- GIT INTEGRATION
    -- ============================================================================
    DiffAdd = { fg = colors.success },
    DiffChange = { fg = colors.warning },
    DiffDelete = { fg = colors.error },
    DiffText = { fg = colors.info, bg = colors.bg_alt },

    -- gitsigns.nvim
    GitSignsAdd = { fg = colors.success },
    GitSignsChange = { fg = colors.warning },
    GitSignsDelete = { fg = colors.error },
    GitSignsAddNr = { fg = colors.success },
    GitSignsChangeNr = { fg = colors.warning },
    GitSignsDeleteNr = { fg = colors.error },
    GitSignsAddLn = { bg = colors.success, fg = colors.bg },
    GitSignsChangeLn = { bg = colors.warning, fg = colors.bg },
    GitSignsDeleteLn = { bg = colors.error, fg = colors.bg },
    GitSignsCurrentLineBlame = { fg = colors.comment },

    -- ============================================================================
    -- PLUGIN SUPPORT
    -- ============================================================================

    -- Telescope.nvim
    TelescopeBorder = { fg = colors.base, bg = colors.bg_alt },
    TelescopeNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopePromptNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopeResultsNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopePreviewNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopeSelection = { fg = colors.bg, bg = colors.base },
    TelescopeSelectionCaret = { fg = colors.base },
    TelescopeMatching = { fg = colors.warning },
    TelescopePromptPrefix = { fg = colors.base },

    -- nvim-cmp
    CmpItemAbbrDeprecated = { fg = colors.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.base },
    CmpItemAbbrMatchFuzzy = { fg = colors.base },
    CmpItemKindVariable = { fg = colors.variable },
    CmpItemKindInterface = { fg = colors.type },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindFunction = { fg = colors.func },
    CmpItemKindMethod = { fg = colors.func },
    CmpItemKindKeyword = { fg = colors.keyword },
    CmpItemKindProperty = { fg = colors.variable },
    CmpItemKindUnit = { fg = colors.number },
    CmpItemKindClass = { fg = colors.type },
    CmpItemKindModule = { fg = colors.type },
    CmpItemKindConstant = { fg = colors.const },
    CmpItemKindEnum = { fg = colors.type },
    CmpItemKindStruct = { fg = colors.type },
    CmpItemKindEvent = { fg = colors.base },
    CmpItemKindOperator = { fg = colors.operator },
    CmpItemKindTypeParameter = { fg = colors.type },

    -- nvim-tree / neo-tree
    NvimTreeNormal = { fg = colors.fg, bg = colors.bg_alt },
    NvimTreeFolderName = { fg = colors.info },
    NvimTreeFolderIcon = { fg = colors.info },
    NvimTreeOpenedFolderName = { fg = colors.base },
    NvimTreeRootFolder = { fg = colors.base },
    NvimTreeSpecialFile = { fg = colors.warning },
    NvimTreeGitDirty = { fg = colors.warning },
    NvimTreeGitNew = { fg = colors.success },
    NvimTreeGitDeleted = { fg = colors.error },

    NeoTreeNormal = { fg = colors.fg, bg = colors.bg_alt },
    NeoTreeDirectoryName = { fg = colors.info },
    NeoTreeDirectoryIcon = { fg = colors.info },
    NeoTreeRootName = { fg = colors.base },
    NeoTreeFileName = { fg = colors.fg },
    NeoTreeFileIcon = { fg = colors.fg },
    NeoTreeGitAdded = { fg = colors.success },
    NeoTreeGitModified = { fg = colors.warning },
    NeoTreeGitDeleted = { fg = colors.error },

    -- Which-key
    WhichKey = { fg = colors.base },
    WhichKeyGroup = { fg = colors.keyword },
    WhichKeyDesc = { fg = colors.fg },
    WhichKeySeparator = { fg = colors.comment },
    WhichKeyFloat = { bg = colors.bg_alt },
    WhichKeyValue = { fg = colors.string },

    -- Indent Blankline
    IblIndent = { fg = colors.bg_alt },
    IblScope = { fg = colors.comment },

    -- Dashboard / Alpha
    DashboardHeader = { fg = colors.base },
    DashboardCenter = { fg = colors.keyword },
    DashboardShortcut = { fg = colors.warning },
    DashboardFooter = { fg = colors.comment },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

M.setup()

return M
