-- vulpes-reddishnovember-light colorscheme
-- Generated by vulpes-theme-lab
-- Comprehensive highlight groups (100+) for maximum legibility

local M = {}

function M.setup()
  vim.cmd('hi clear')
  if vim.fn.exists('syntax_on') then
    vim.cmd('syntax reset')
  end

  vim.o.background = 'light'
  vim.g.colors_name = 'vulpes-reddishnovember-light'

  local colors = {
    bg = '#f7f7f7',
    bg_alt = '#efefef',
    fg = '#501630',
    base = '#fa0070',

    error = '#e0001a',
    warning = '#e0001e',
    success = '#d60044',
    info = '#e00083',
    hint = '#ff2e8c',

    -- Diff-specific colors (traditional green/red for instant recognition)
    diff_add = '#116329',      -- Deeper forest green
    diff_delete = '#cb2431',   -- GitHub-style red
    diff_change = '#b08800',   -- Darker yellow/orange for light bg
    diff_text = '#005cc5',     -- Blue for changed text within line

    comment = '#000000',
    keyword = '#000000',
    string = '#000000',
    number = '#fa00b3',
    boolean = '#ef0034',
    func = '#e0001e',
    const = '#ef0034',
    type = '#e5008d',
    variable = '#f5007e',
    operator = '#e0005d',
    builtin = '#ea0042',
    parameter = '#ef0074',
    property = '#f50087',
    namespace = '#e0004e',
    macro = '#e50086',
    tag = '#db0045',
    punctuation = '#fa006c',
    heading = '#d6002e',

    selection = '#00d9ff',      -- Cyberpunk cyan/blue
    selection_fg = '#0d0d0d',   -- Dark fg for contrast
    cursor = '#fa0070',
    cursorline = '#f3f3f3',
  }

  local highlights = {
    -- ============================================================================
    -- EDITOR UI
    -- ============================================================================
    Normal = { fg = colors.fg, bg = 'none' },
    NormalFloat = { fg = colors.fg, bg = colors.bg_alt },
    NormalNC = { fg = colors.fg, bg = 'none' },
    FloatBorder = { fg = colors.base, bg = colors.bg_alt },
    FloatTitle = { fg = colors.base, bg = colors.bg_alt },

    Cursor = { fg = colors.bg, bg = colors.cursor },
    lCursor = { link = 'Cursor' },
    CursorIM = { link = 'Cursor' },
    TermCursor = { link = 'Cursor' },
    TermCursorNC = { fg = colors.bg, bg = colors.comment },

    CursorLine = { bg = colors.cursorline },
    CursorColumn = { bg = colors.cursorline },
    CursorLineNr = { fg = colors.base },
    LineNr = { fg = colors.comment },
    LineNrAbove = { fg = colors.comment },
    LineNrBelow = { fg = colors.comment },

    SignColumn = { bg = 'none' },
    SignColumnSB = { link = 'SignColumn' },
    FoldColumn = { fg = colors.comment, bg = 'none' },
    Folded = { fg = colors.comment, bg = colors.bg_alt },
    ColorColumn = { bg = colors.bg_alt },

    -- Selections & Search
    Visual = { fg = colors.selection_fg, bg = colors.selection },
    VisualNOS = { fg = colors.selection_fg, bg = colors.selection },
    Search = { fg = colors.bg, bg = colors.warning },
    IncSearch = { fg = colors.bg, bg = colors.base },
    CurSearch = { fg = colors.bg, bg = colors.base },
    Substitute = { fg = colors.bg, bg = colors.error },

    -- UI Elements
    Pmenu = { fg = colors.fg, bg = colors.bg_alt },
    PmenuSel = { fg = colors.bg, bg = colors.base },
    PmenuSbar = { bg = colors.bg_alt },
    PmenuThumb = { bg = colors.base },
    PmenuKind = { fg = colors.type, bg = colors.bg_alt },
    PmenuKindSel = { fg = colors.bg, bg = colors.type },
    PmenuExtra = { fg = colors.comment, bg = colors.bg_alt },
    PmenuExtraSel = { fg = colors.bg, bg = colors.comment },

    StatusLine = { fg = colors.fg, bg = colors.bg_alt },
    StatusLineNC = { fg = colors.comment, bg = 'none' },
    WinBar = { fg = colors.fg, bg = 'none' },
    WinBarNC = { fg = colors.comment, bg = 'none' },

    TabLine = { fg = colors.comment, bg = 'none' },
    TabLineFill = { bg = 'none' },
    TabLineSel = { fg = colors.fg, bg = colors.bg_alt },

    VertSplit = { fg = colors.bg_alt },
    WinSeparator = { fg = colors.bg_alt },

    Title = { fg = colors.base },
    Directory = { fg = colors.info },
    Question = { fg = colors.success },
    MoreMsg = { fg = colors.success },
    ModeMsg = { fg = colors.base },
    WarningMsg = { fg = colors.warning },
    ErrorMsg = { fg = colors.error },

    Conceal = { fg = colors.comment },
    NonText = { fg = colors.comment },
    SpecialKey = { fg = colors.comment },
    Whitespace = { fg = '#d8d0d4' },  -- Dimmer than comments
    EndOfBuffer = { fg = 'none' },

    -- Matching brackets
    MatchParen = { fg = colors.warning, bg = '#ffe0b0', bold = true },

    -- Spell checking
    SpellBad = { sp = colors.error, undercurl = true },
    SpellCap = { sp = colors.warning, undercurl = true },
    SpellLocal = { sp = colors.info, undercurl = true },
    SpellRare = { sp = colors.hint, undercurl = true },

    -- ============================================================================
    -- CORE SYNTAX HIGHLIGHTING
    -- ============================================================================
    Comment = { fg = colors.comment },
    SpecialComment = { fg = colors.comment },

    Constant = { fg = colors.const },
    String = { fg = colors.string },
    Character = { fg = colors.string },
    Number = { fg = colors.number },
    Boolean = { fg = colors.boolean },
    Float = { fg = colors.number },

    Identifier = { fg = colors.variable },
    Function = { fg = colors.func },

    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.keyword },
    Repeat = { fg = colors.keyword },
    Label = { fg = colors.keyword },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword },
    Exception = { fg = colors.error },

    PreProc = { fg = colors.base },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Macro = { fg = colors.macro },
    PreCondit = { fg = colors.keyword },

    Type = { fg = colors.type },
    StorageClass = { fg = colors.keyword },
    Structure = { fg = colors.type },
    Typedef = { fg = colors.type },

    Special = { fg = colors.base },
    SpecialChar = { fg = colors.base },
    Tag = { fg = colors.tag },
    Delimiter = { fg = colors.punctuation },
    Debug = { fg = colors.warning },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    Ignore = { fg = colors.comment },
    Error = { fg = colors.error },
    Todo = { fg = colors.bg, bg = colors.warning },

    -- ============================================================================
    -- LSP DIAGNOSTICS
    -- ============================================================================
    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.info },
    DiagnosticHint = { fg = colors.hint },
    DiagnosticOk = { fg = colors.success },

    DiagnosticVirtualTextError = { fg = colors.error, bg = 'none' },
    DiagnosticVirtualTextWarn = { fg = colors.warning, bg = 'none' },
    DiagnosticVirtualTextInfo = { fg = colors.info, bg = 'none' },
    DiagnosticVirtualTextHint = { fg = colors.hint, bg = 'none' },

    DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.warning, underline = true },
    DiagnosticUnderlineInfo = { sp = colors.info, underline = true },
    DiagnosticUnderlineHint = { sp = colors.hint, underline = true },

    DiagnosticFloatingError = { fg = colors.error, bg = colors.bg_alt },
    DiagnosticFloatingWarn = { fg = colors.warning, bg = colors.bg_alt },
    DiagnosticFloatingInfo = { fg = colors.info, bg = colors.bg_alt },
    DiagnosticFloatingHint = { fg = colors.hint, bg = colors.bg_alt },

    DiagnosticSignError = { fg = colors.error, bg = 'none' },
    DiagnosticSignWarn = { fg = colors.warning, bg = 'none' },
    DiagnosticSignInfo = { fg = colors.info, bg = 'none' },
    DiagnosticSignHint = { fg = colors.hint, bg = 'none' },

    -- LSP References (highlight symbol under cursor)
    LspReferenceText = { bg = '#f0e8ec' },
    LspReferenceRead = { bg = '#f0e8ec' },
    LspReferenceWrite = { bg = '#e8d8e0' },  -- Slightly darker for writes

    -- LSP Semantic Token Groups
    ['@lsp.type.class'] = { link = 'Type' },
    ['@lsp.type.decorator'] = { link = 'Function' },
    ['@lsp.type.enum'] = { link = 'Type' },
    ['@lsp.type.enumMember'] = { link = 'Constant' },
    ['@lsp.type.function'] = { link = 'Function' },
    ['@lsp.type.interface'] = { link = 'Type' },
    ['@lsp.type.macro'] = { link = 'Macro' },
    ['@lsp.type.method'] = { link = 'Function' },
    ['@lsp.type.namespace'] = { fg = colors.namespace },
    ['@lsp.type.parameter'] = { fg = colors.parameter },
    ['@lsp.type.property'] = { fg = colors.property },
    ['@lsp.type.struct'] = { link = 'Type' },
    ['@lsp.type.type'] = { link = 'Type' },
    ['@lsp.type.typeParameter'] = { link = 'Type' },
    ['@lsp.type.variable'] = { link = '@variable' },

    -- ============================================================================
    -- TREESITTER - COMPREHENSIVE LANGUAGE SUPPORT
    -- ============================================================================

    -- Comments
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { fg = colors.comment },
    ['@comment.error'] = { fg = colors.error },
    ['@comment.warning'] = { fg = colors.warning },
    ['@comment.todo'] = { fg = colors.bg, bg = colors.warning },
    ['@comment.note'] = { fg = colors.info },

    -- Constants
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = colors.const },
    ['@constant.macro'] = { link = 'Macro' },

    -- Strings
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { fg = colors.string },
    ['@string.regex'] = { fg = colors.warning },
    ['@string.escape'] = { fg = colors.base },
    ['@string.special'] = { fg = colors.base },
    ['@string.special.symbol'] = { fg = colors.const },
    ['@string.special.url'] = { fg = colors.info, underline = true },

    -- Characters & Numbers
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@boolean'] = { link = 'Boolean' },

    -- Functions
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = colors.builtin },
    ['@function.call'] = { fg = colors.func },
    ['@function.macro'] = { link = 'Macro' },
    ['@function.method'] = { fg = colors.func },
    ['@function.method.call'] = { fg = colors.func },

    -- Constructors
    ['@constructor'] = { fg = colors.type },

    -- Keywords
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.return'] = { fg = colors.keyword },
    ['@keyword.function'] = { fg = colors.keyword },
    ['@keyword.operator'] = { fg = colors.operator },
    ['@keyword.import'] = { link = 'Include' },
    ['@keyword.exception'] = { link = 'Exception' },
    ['@keyword.directive'] = { link = 'PreProc' },
    ['@keyword.directive.define'] = { link = 'Define' },

    -- Operators
    ['@operator'] = { link = 'Operator' },

    -- Variables
    ['@variable'] = { fg = colors.variable },
    ['@variable.builtin'] = { fg = colors.builtin },
    ['@variable.parameter'] = { fg = colors.parameter },
    ['@variable.parameter.builtin'] = { fg = colors.builtin },
    ['@variable.member'] = { fg = colors.property },

    -- Types
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { fg = colors.builtin },
    ['@type.definition'] = { link = 'Typedef' },
    ['@type.qualifier'] = { link = 'Keyword' },

    -- Attributes & Properties
    ['@attribute'] = { fg = colors.base },
    ['@attribute.builtin'] = { fg = colors.builtin },
    ['@property'] = { fg = colors.property },
    ['@field'] = { fg = colors.property },

    -- Modules & Namespaces
    ['@module'] = { fg = colors.namespace },
    ['@module.builtin'] = { fg = colors.builtin },
    ['@label'] = { link = 'Label' },

    -- Punctuation
    ['@punctuation.delimiter'] = { fg = colors.punctuation },
    ['@punctuation.bracket'] = { fg = colors.punctuation },
    ['@punctuation.special'] = { fg = colors.punctuation },

    -- Tags (HTML/XML/JSX)
    ['@tag'] = { fg = colors.tag },
    ['@tag.builtin'] = { fg = colors.builtin },
    ['@tag.attribute'] = { fg = colors.property },
    ['@tag.delimiter'] = { fg = colors.punctuation },

    -- Markup (Markdown, etc.)
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.underline'] = { underline = true },

    ['@markup.heading'] = { fg = colors.heading },
    ['@markup.heading.1'] = { fg = colors.heading },
    ['@markup.heading.2'] = { fg = colors.heading },
    ['@markup.heading.3'] = { fg = colors.heading },
    ['@markup.heading.4'] = { fg = colors.heading },
    ['@markup.heading.5'] = { fg = colors.heading },
    ['@markup.heading.6'] = { fg = colors.heading },

    ['@markup.quote'] = { fg = colors.comment },
    ['@markup.math'] = { fg = colors.number },

    ['@markup.link'] = { fg = colors.info, underline = true },
    ['@markup.link.label'] = { fg = colors.string },
    ['@markup.link.url'] = { fg = colors.info, underline = true },

    ['@markup.raw'] = { fg = colors.string },
    ['@markup.raw.block'] = { fg = colors.string },

    ['@markup.list'] = { fg = colors.base },
    ['@markup.list.checked'] = { fg = colors.success },
    ['@markup.list.unchecked'] = { fg = colors.comment },

    -- Diffs (treesitter)
    ['@diff.plus'] = { fg = colors.diff_add, bold = true },
    ['@diff.minus'] = { fg = colors.diff_delete, italic = true },
    ['@diff.delta'] = { fg = colors.diff_change },

    -- ============================================================================
    -- GIT INTEGRATION (traditional green/red for diffs)
    -- ============================================================================
    DiffAdd = { fg = colors.diff_add, bold = true },
    DiffChange = { fg = colors.diff_change },
    DiffDelete = { fg = colors.diff_delete, italic = true },
    DiffText = { fg = colors.diff_text, bg = colors.bg_alt },

    -- Added/Removed (used by some diff views)
    Added = { fg = colors.diff_add, bold = true },
    Removed = { fg = colors.diff_delete, italic = true },
    Changed = { fg = colors.diff_change },

    -- gitsigns.nvim
    GitSignsAdd = { fg = colors.diff_add },
    GitSignsChange = { fg = colors.diff_change },
    GitSignsDelete = { fg = colors.diff_delete },
    GitSignsAddNr = { fg = colors.diff_add },
    GitSignsChangeNr = { fg = colors.diff_change },
    GitSignsDeleteNr = { fg = colors.diff_delete },
    GitSignsAddLn = { bg = '#d4edda' },  -- Light green bg
    GitSignsChangeLn = { bg = '#fff3cd' },  -- Light yellow bg
    GitSignsDeleteLn = { bg = '#f8d7da' },  -- Light red bg
    GitSignsCurrentLineBlame = { fg = colors.comment },

    -- mini.diff
    MiniDiffSignAdd = { fg = colors.diff_add, bold = true },
    MiniDiffSignChange = { fg = colors.diff_change },
    MiniDiffSignDelete = { fg = colors.diff_delete, italic = true },
    MiniDiffOverAdd = { bg = '#d4edda', bold = true },
    MiniDiffOverChange = { bg = '#fff3cd' },
    MiniDiffOverContext = { bg = colors.bg_alt },
    MiniDiffOverDelete = { bg = '#f8d7da', fg = colors.diff_delete, italic = true },

    -- ============================================================================
    -- PLUGIN SUPPORT
    -- ============================================================================

    -- Telescope.nvim
    TelescopeBorder = { fg = colors.base, bg = colors.bg_alt },
    TelescopeNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopePromptNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopeResultsNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopePreviewNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopeSelection = { fg = colors.bg, bg = colors.base },
    TelescopeSelectionCaret = { fg = colors.base },
    TelescopeMatching = { fg = colors.warning },
    TelescopePromptPrefix = { fg = colors.base },

    -- nvim-cmp
    CmpItemAbbrDeprecated = { fg = colors.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.base },
    CmpItemAbbrMatchFuzzy = { fg = colors.base },
    CmpItemKindVariable = { fg = colors.variable },
    CmpItemKindInterface = { fg = colors.type },
    CmpItemKindText = { fg = colors.fg },
    CmpItemKindFunction = { fg = colors.func },
    CmpItemKindMethod = { fg = colors.func },
    CmpItemKindKeyword = { fg = colors.keyword },
    CmpItemKindProperty = { fg = colors.variable },
    CmpItemKindUnit = { fg = colors.number },
    CmpItemKindClass = { fg = colors.type },
    CmpItemKindModule = { fg = colors.type },
    CmpItemKindConstant = { fg = colors.const },
    CmpItemKindEnum = { fg = colors.type },
    CmpItemKindStruct = { fg = colors.type },
    CmpItemKindEvent = { fg = colors.base },
    CmpItemKindOperator = { fg = colors.operator },
    CmpItemKindTypeParameter = { fg = colors.type },

    -- nvim-tree / neo-tree
    NvimTreeNormal = { fg = colors.fg, bg = colors.bg_alt },
    NvimTreeFolderName = { fg = colors.info },
    NvimTreeFolderIcon = { fg = colors.info },
    NvimTreeOpenedFolderName = { fg = colors.base },
    NvimTreeRootFolder = { fg = colors.base },
    NvimTreeSpecialFile = { fg = colors.warning },
    NvimTreeGitDirty = { fg = colors.warning },
    NvimTreeGitNew = { fg = colors.success },
    NvimTreeGitDeleted = { fg = colors.error },

    NeoTreeNormal = { fg = colors.fg, bg = colors.bg_alt },
    NeoTreeDirectoryName = { fg = colors.info },
    NeoTreeDirectoryIcon = { fg = colors.info },
    NeoTreeRootName = { fg = colors.base },
    NeoTreeFileName = { fg = colors.fg },
    NeoTreeFileIcon = { fg = colors.fg },
    NeoTreeGitAdded = { fg = colors.success },
    NeoTreeGitModified = { fg = colors.warning },
    NeoTreeGitDeleted = { fg = colors.error },

    -- Which-key
    WhichKey = { fg = colors.base },
    WhichKeyGroup = { fg = colors.keyword },
    WhichKeyDesc = { fg = colors.fg },
    WhichKeySeparator = { fg = colors.comment },
    WhichKeyFloat = { bg = colors.bg_alt },
    WhichKeyValue = { fg = colors.string },

    -- Indent Blankline
    IblIndent = { fg = colors.bg_alt },
    IblScope = { fg = colors.comment },

    -- Dashboard / Alpha
    DashboardHeader = { fg = colors.base },
    DashboardCenter = { fg = colors.keyword },
    DashboardShortcut = { fg = colors.warning },
    DashboardFooter = { fg = colors.comment },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

M.setup()

return M
